# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(802, 511)
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 801, 511))
        self.label.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border : 2px Solid White")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Frame)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 781, 311))
        self.label_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border : 2px Solid White")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:/Users/HKTech/Downloads/voice.gif"))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Frame)
        self.label_3.setGeometry(QtCore.QRect(10, 330, 601, 171))
        self.label_3.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border : 2px Solid White")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Frame)
        self.label_4.setGeometry(QtCore.QRect(620, 330, 171, 171))
        self.label_4.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border : 2px Solid White")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(Frame)
        self.pushButton.setGeometry(QtCore.QRect(630, 400, 151, 41))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setMouseTracking(False)
        self.pushButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border : 2px Solid white;\n"
"font: 26pt \"Times New Roman\";\n"
"color : rgb(255, 255, 255)\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(Frame)
        self.textBrowser.setGeometry(QtCore.QRect(630, 340, 151, 51))
        self.textBrowser.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border : 2px Solid white;\n"
"font: 20pt \"Times New Roman\";\n"
"color : rgb(255, 255, 255)")
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_1 = QtWidgets.QPushButton(Frame)
        self.pushButton_1.setGeometry(QtCore.QRect(630, 450, 151, 41))
        self.pushButton_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_1.setMouseTracking(False)
        self.pushButton_1.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border : 2px Solid white;\n"
"font: 26pt \"Times New Roman\";\n"
"color : rgb(255, 255, 255)\n"
"")
        self.pushButton_1.setObjectName("pushButton_1")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Frame)
        self.textBrowser_2.setGeometry(QtCore.QRect(20, 340, 581, 151))
        self.textBrowser_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border : 2px Solid white;\n"
"font: 20pt \"Times New Roman\";\n"
"color : rgb(255, 255, 255)")
        self.textBrowser_2.setObjectName("textBrowser_2")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "KALI"))
        self.pushButton.setText(_translate("Frame", "START"))
        self.textBrowser.setHtml(_translate("Frame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_1.setText(_translate("Frame", "STOP"))
        self.textBrowser_2.setHtml(_translate("Frame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
